### ISSUE TITLE
闪退呀

### ISSUE THREAD

**Issue by clock8863** [ying-ck/fanqienovel-downloader#1]
这个输入id之久enter就闪退了呀

**Comment by ying-ck** [comment]
确定是有效id吗？
![屏幕截图 2024-08-01 172553](https://github.com/user-attachments/assets/53545106-54a7-4925-bf7c-6ab9daaf89e9)

**Comment by ying-ck** [comment]
v1.0.1版本应该不会出现此问题

**Comment by clock8863** [comment]
不好意思，我的问题，我输入了错误的id，qwq
