### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by MichaelNec** [ying-ck/fanqienovel-downloader#14]
![1](https://github.com/user-attachments/assets/dd172774-c761-4b82-8054-b64f1f8baabc)

**Comment by qxqycb** [comment]
具体报错内容是什么呢？
你可能使用的是之前的v1.07版本，第一次打开时确实会报错，请下载最新版本的v1.08(beta)版

**Comment by qxqycb** [comment]
应该可以使用
