### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by MachMY** [ying-ck/fanqienovel-downloader#15]
1）各章节之间可以空一行，以方便阅读
2）有一些小说里有配图，能否让api也爬取图片？（据说难度很高）

**Comment by qxqycb** [comment]
> 1）各章节之间可以空一行，以方便阅读
> 2）有一些小说里有配图，能否让api也爬取图片？（据说难度很高）

目前使用的API暂时没有爬取图片的功能，且保存方式是txt文件，无法支持插入图片，倒是空行可以加，今天一定做出来

**Comment by qxqycb** [comment]
空行功能已在v1.0.8中加入，[链接](https://github.com/ying-ck/fanqienovel-downloader/releases/tag/v1.0.8)
