### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SteveSteve666** [ying-ck/fanqienovel-downloader#16]
![mmexport1724025062782.png](https://github.com/user-attachments/assets/02056715-be3a-4706-a5a1-d13e8835df3f)
更了最新的1.0.8之后进入程序前一两秒是1.0.8然后突然就变成1.0.7，下载小说就报错，这是哪的问题

**Comment by qxqycb** [comment]
稍等，正在修改

**Comment by ying-ck** [comment]
已经解决问题，请使用最新版程序。
