### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SteveSteve666** [ying-ck/fanqienovel-downloader#17]
![PixPin_2024-08-19_15-02-45](https://github.com/user-attachments/assets/e21e0ba3-a2c6-4678-89a3-c457b80aa950)
这个是哪里的问题😂

**Comment by ying-ck** [comment]
网络方面的问题。每次都是这样吗？

**Comment by SteveSteve666** [comment]
哦可以了，我宽带的问题，不好意思
