### ISSUE TITLE
全角空格

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#19]
作者你好！
真诚希望能把段首空格变成全角空格：“　”
或者在config中加一个开关来控制全角和半角，万分感谢~

**Comment by qxqycb** [comment]
为什么要段首空格变成全角空格呢？你说一下原因

**Comment by doggybread** [comment]
嗯，下面详细解释一下我遇到的问题。
注：示例中所有小说都是用1.0.7版本下载的。

情况一、阅读软件 Koodo Reader

我下载后的小说，大多是以“引用”方式在Koodo Reader中打开的，这样每天凌晨自动更新之后，打开KoodoReader就可以继续阅读新章节，非常Nice！
在阅读时我希望段首能缩进两个汉字空格。但问题是，即使我在“fanqienovel-downloader-v1.0.7中”设置了段首4个空格，也会出现很奇怪的现象，如下图所示：

文本编辑器中显示，下载后TXT小说已经有了四个段首空格：
![排版0](https://github.com/user-attachments/assets/8b0b73c6-b889-4787-b707-5e02e2eb5270)

但在阅读器中显示结果是这样的：
![排版1](https://github.com/user-attachments/assets/63c3aec1-33a2-4bf1-9b3f-c235828a770a)

而当我在编辑器中把四个半角空格换成两个全角空格后：
![排版A0](https://github.com/user-attachments/assets/5261e10b-2ce6-4d4d-b815-586a5cc473d4)

koodo Reader中显示结果就比较理想：
![排版A1](https://github.com/user-attachments/assets/f32302ee-b353-4eab-85f0-ca327fb368f4)

我想这也许是KoodoReader的问题，找他们解决空格不显示的问题应该是最优解，直到发现Calibre在将TXT转换成EPub格式时，问题同样存在，我就觉得从源头上用全角空格代替半角空格可能是当前最快速解决问题的方法了。

情况如下：

众所周知，Calibre可以将Txt小说转换成Epub格式。
当我转换段首有四个半角空格的小说时，得到的Epub文件打开是这样的：

![排版B3](https://github.com/user-attachments/assets/60d82f62-b0a2-4f37-8331-e054449de900)

而当换成两个全角空格后，效果如下：
![排版B2](https://github.com/user-attachments/assets/45fb4013-6bc5-4590-98a7-a6b88ddc445b)


——
综上，虽然可能上述这些工具都存在段首缩进问题的BUG，但因为番茄小说下载工具主要功能就是下载中文小说，我觉得如果用全角空格代替半角空格（或者设置开关），也许是当前最简单的解决方案。

当然，如果作者觉得麻烦也不用改，毕竟手动排版处理一下也不算太麻烦，但如果能够采纳，还是很让人感动滴！

BTW：downloader工具很棒！

**Comment by qxqycb** [comment]
你这个KoodoReader可能将半角空格识别成了下载时的错误空格，因为有4个半角空格，但是一般只有2个段首空格，从而自动删除

**Comment by qxqycb** [comment]
感谢你的意见，这个功能会上线的

**Comment by qxqycb** [comment]
新的版本已上线，请下载最新版本
