### ISSUE TITLE
下载的小说内容是空

### ISSUE THREAD

**Issue by wangfuke3020** [ying-ck/fanqienovel-downloader#20]
使用最新版的下载的小说内容是空的，并且有的直接输入ID，会闪退，例如：7391853045245561880 这个ID软件也会闪退

**Comment by qxqycb** [comment]
我用了你的id试了，没问题啊？
你把报错截图发来看看

**Comment by ying-ck** [comment]
[张家古楼拆迁，我守护终极被曝光.txt](https://github.com/user-attachments/files/16689455/default.txt)
确实是可以下载的，你可以看看是不是网络问题。
