### ISSUE TITLE
/bin/sh: title: command not found

### ISSUE THREAD

**Issue by cikichen** [ying-ck/fanqienovel-downloader#21]
本程序完全免费。
Github: https://github.com/ying-ck/fanqienovel-downloader
作者：Yck & qxqycb

输入书的id直接下载
输入下面的数字进入其他功能:

1. 更新小说
2. 搜索
3. 批量下载
4. 设置
5. 退出

/bin/sh: title: command not found

Mac上运行中是报这个错，但是不影响功能

**Comment by qxqycb** [comment]
在 Mac 上运行程序时出现 “/bin/sh：标题：未找到命令” 错误，可能有以下几种原因及解决方法：
一、命令拼写错误
可能是你在命令行中输入的命令存在拼写错误。仔细检查你输入的命令，确保每个单词都是正确的，并且符合命令的语法规则。
二、环境变量问题
检查环境变量配置：环境变量可能没有正确设置，导致系统无法找到特定的命令。可以通过查看 $PATH 环境变量来确定系统在哪些目录中查找可执行文件。在终端中输入 echo $PATH，查看输出的路径列表。确保包含了应该包含的目录，例如 /usr/bin 和 /bin 等。
如果必要，可以手动添加路径到环境变量中。例如，如果你的命令所在的目录是 /usr/local/bin，可以通过在终端中输入以下命令将其添加到 $PATH 中：export PATH=$PATH:/usr/local/bin。注意，这种方式只是临时修改环境变量，如果你希望永久修改，需要编辑相应的配置文件，如 ~/.bash_profile 或 ~/.zshrc。
三、软件安装问题
确认相关软件已正确安装：如果错误是由于特定软件的命令无法找到引起的，确保该软件已正确安装在你的系统上。可以通过重新安装软件或者检查软件的安装目录来确认。
检查软件的安装路径：有时候软件可能安装在非标准的目录中，导致系统无法找到其命令。你可以通过在终端中输入 which 命令名（例如 which 标题，如果这是一个特定软件的命令）来查找命令的实际路径。如果找到了路径，但仍然出现错误，可能是软件的安装有问题或者与系统的兼容性存在问题。
四、文件权限问题
检查文件权限：如果命令对应的文件权限不正确，也可能导致无法执行。可以使用 ls -l 文件名（例如 ls -l 标题文件，如果有特定的文件与错误相关）来查看文件的权限。确保文件具有可执行权限（对于脚本文件，通常需要 x 权限）。
如果文件没有可执行权限，可以使用 chmod 命令来添加权限。例如，对于一个脚本文件，可以使用 chmod +x 文件名 来添加可执行权限。
如果以上方法都无法解决问题，你可以提供更多关于出现错误的上下文信息，例如具体是在执行什么操作时出现的错误，以及相关的命令或软件的详细情况，以便更准确地诊断问题。

**Comment by ying-ck** [comment]
是因为程序使用了os.popen('title xxxxx')
现已删除
