### ISSUE TITLE
下载器无法使用

### ISSUE THREAD

**Issue by libbyyt** [ying-ck/fanqienovel-downloader#24]
番茄的网站有这本小说：https://fanqienovel.com/page/6901548371333352456?enter_from=search
但是下载器中输入链接以及id的时候，均提示不存在
![屏幕截图 2024-08-27 190926](https://github.com/user-attachments/assets/7840175a-71e1-4871-af9d-46f58bc9fce4)

**Comment by libbyyt** [comment]
![屏幕截图 2024-08-27 192231](https://github.com/user-attachments/assets/edd2e923-f821-4edd-8605-d3b2281a1b6b)
点击更新小说的时候报错，我是win11系统，使用兼容性模式运行该程序，同样的报错提示

**Comment by qxqycb** [comment]
GUI界面的程序目前还在测试中，感谢你的反馈
