### ISSUE TITLE
疑似出现客户端ID保护

### ISSUE THREAD

**Issue by NLQF** [ying-ck/fanqienovel-downloader#26]
我发现在番茄小说APP里面的小说文件，通过分享得出来的链接ID是可以正常用来下载小说的。
但在电脑网页“番茄小说网”直接提取出来的链接却无法被识别，显示“该书不存在或ID错误”。

拿一个抖音热文来举例子吧：
这是电脑端打开番茄小说后直接在浏览器里面提取出来的链接（https://fanqienovel.com/reader/7362835634320313344）
而这是在手机端分享后提取出来的链接（https://changdunovel.com/wap/share-v2.html?aid=1967&book_id=7361288887009823768&share_type=0&share_code=7z-MbBYOV9wEsennr5Ak8bOQnwqqdaYNmL_yj0_NK6E%3D&uid=c175eb3cad1fa56a992ab6592b51a270&share_id=o7lEnUTveWNwVhbwRUNQG3f7_x5NsnvIy_yMLMKWAEI%3D&zlink=https%3A%2F%2Fzlink.fqnovel.com%2FJkKw2&gd_label=click_schema_lhft_44754235a&use_open_launch_app=1&source_channel=wechat_chat&type=book&share_token=ca9e0b4b-411e-428e-a6ef-bd4e1e0567ee）

我们可以看到电脑端是以reader为结尾的网址，但手机端以book _id为主。

此时我们就会发现电脑端所看到的链接和手机分享出来的链接的ID完全不一样，电脑端是（7362835634320313344），而手机端是（7361288887009823768）

我把这两串ID都放进小说下载器试一下，结果就是：
电脑端的ID无法被识别，但手机端分享链接的ID却可以成功识别并下载。

最后讲一下这个手机APP链接是如何提取的：在番茄小说APP点开你要看的文章，在右上角有一个分享，由于番茄小说并没有直接复制链接的功能，所以我们把它发送到微信（其他软件目前为止没试过），随后在电脑微信端点开这个分享的东西（见附件），随后在弹出来的新窗口中选择用系统浏览器打开，最后再用系统浏览器单独把ID提取出来，复制到小说下载器里面去下载。

总结：番茄的电脑端跟手机端用的应该不是同一个API，导致了电脑的ID和手机ID出现不一样的情况，也有可能是软件并没有识别多ID的功能，导致只能使用手机端的ID。希望作者可以针对这个问题进行一些调整，希望作者可以把这个软件做的更好！
![微信图片_20240828192224](https://github.com/user-attachments/assets/08099f45-7011-4879-88c9-fdc15fabd4cf)

**Comment by qxqycb** [comment]
你这个浏览器里面提取出来的链接(https://fanqienovel.com/reader/7362835634320313344)是某一章的小说页面链接，我们程序解析的是小说目录链接

**Comment by NLQF** [comment]
谢谢！

**Comment by qxqycb** [comment]
还是感谢你！
有了新的思路

**Comment by NLQF** [comment]
用章节ID（即上文的电脑端 reader/***数字***） 来反推这本书的book_id我感觉还是有点困难，但我相信作者一定可以成功的！

**Comment by qxqycb** [comment]
例如你的小说的某一章：
![image](https://github.com/user-attachments/assets/faee3f3e-a459-46bd-aee9-277dce7659dd)
点“目录”
![image](https://github.com/user-attachments/assets/593d44a2-425f-4374-a3bb-f8c91782ba0c)
再点书名就是目录的链接

**Comment by qxqycb** [comment]
但是还有一一种办法：用Selenium

**Comment by NLQF** [comment]
谢谢开发者，我的问题已经完全解决了！(=^▽^=)

顺便想问一下，因为下载小说软件是直接用Python的窗口来执行的，那作者以后会打算出一个exe程序吗？一定期待~

exe可能操作方便，但维护麻烦。
直接更改文件夹内容的py文件可能方便，但不怎么美观hhh

（如果exe比较麻烦，那就算了，我只是有这个想法而已( ‘-ωก̀ )）

**Comment by NLQF** [comment]
不懂但赞同hhh
![Screenshot_2024-08-29-12-01-29-408_com microsoft emmx-edit](https://github.com/user-attachments/assets/bf2b8de6-a097-49cd-bac0-0ebd12c3ab39)

**Comment by NLQF** [comment]
对了，还有一个问题。作者的程序里面有个更新选项，如果出现了一个这么问题：

下载了小说的章节1、2、3、4、5，

但是假如我一不小心删掉了 章节3 ，

使用程序“更新”选项，会不会把 章节3 重新下载回来？

**Comment by qxqycb** [comment]
会下载回来(只要你不把data文件夹中小说对应的json文件删了)

**Comment by NLQF** [comment]
好，谢谢！

**Comment by yan-qy** [comment]
不对，说错了，不会下载

**Comment by qxqycb** [comment]
不对，说错了，不会下载

**Comment by qxqycb** [comment]
但是你可以把data文件夹中小说对应的json文件删了，就会重新下载一次

**Comment by NLQF** [comment]
会不会造成下载文件重复૮ ºﻌºა

**Comment by qxqycb** [comment]
不会
