### ISSUE TITLE
1.1.3版本闪退

### ISSUE THREAD

**Issue by WanFeng2025** [ying-ck/fanqienovel-downloader#27]
1.1.3版无论是fast版还是原版都闪退 1.1.2可以正常使用
系统版本win11 23H2 22631.4037 
python版本3.10.6 64位
闪退前截图：
![111](https://github.com/user-attachments/assets/fe553376-ca3a-41ec-9f24-d0dd1b63b6e3)
![112](https://github.com/user-attachments/assets/3c10ae07-b3e6-4fb2-81ee-2d94aa9126cf)
有data文件夹生成 config.json里有{"kg": 0, "kgf": "\u3000", "delay": [50, 150], "save_path": "", "save_mode": 1, "space_mode": "halfwidth"}
record.json里有[]
bookstore文件夹为空

**Comment by qxqycb** [comment]
你这是网络错误，是不是开了代理？如果开了先关一下试试

**Comment by WanFeng2025** [comment]
非常感谢二位 确实是网络问题
