### ISSUE TITLE
当爬取小说为分卷小说时，章节序号仍然依次排序

### ISSUE THREAD

**Issue by yuangqian108** [ying-ck/fanqienovel-downloader#3]
当爬取小说为分卷小说时，章节序号仍然依次排序   测试小说id 7397693122731330622 共计50章左右

**Comment by ying-ck** [comment]
所以希望如何排序呢？

**Comment by yuangqian108** [comment]
![Screenshot_2024-08-06-16-49-14-080_mark via gp](https://github.com/user-attachments/assets/dbb99ba8-b75b-49a8-998f-1ff56364b48f)希望可以章节序号可以与原章节序号保持一致

**Comment by yuangqian108** [comment]
![IMG_20240806_165207](https://github.com/user-attachments/assets/6c40fc53-bbfe-46a0-933b-c175e9e0474c)
希望爬取小说章节序号与原文章节序号一致。

**Comment by ying-ck** [comment]
![屏幕截图 2024-08-06 175051](https://github.com/user-attachments/assets/d5d2cca3-8e86-41f6-801d-b4e229de5caf)
我这边是按照章节下载的，你下的时候是怎么样的？
