### ISSUE TITLE
提几点优化建议

### ISSUE THREAD

**Issue by BUnipendix** [ying-ck/fanqienovel-downloader#32]
1. 解密文章内容的时候建议使用python自带的str.translate，不仅代码简洁而且效率高，经测试速度能提高上百倍
2. 缓存建议使用自定义的支持追加写入的文件格式，用json每次都要覆盖一遍文件
3. config使用中文和缩进，方便理解和修改
（后面可能会追加）

**Comment by qxqycb** [comment]
感谢反馈😀

**Comment by qxqycb** [comment]
对于你的建议：
> 1. 解密文章内容的时候建议使用python自带的str.translate，不仅代码简洁而且效率高，经测试速度能提高上百倍

给予修改
> 2.缓存建议使用自定义的支持追加写入的文件格式，用json每次都要覆盖一遍文件

不予修改，因为使用json文件覆盖一遍文件是为了防止用户使用时报错退出，使用自定义的支持追加写入的文件格式无法及时保存

> 3.config使用中文和缩进，方便理解和修改
（后面可能会追加）

不予修改，没有意义

**Comment by qxqycb** [comment]
最后，感谢你的反馈
