### ISSUE TITLE
设置保存为epub格式后，软件会闪退

### ISSUE THREAD

**Issue by XiaoHuangJiYa** [ying-ck/fanqienovel-downloader#35]
v1.14版本
设置保存为epub格式后，软件下载小说时会闪退
通过命令提示符调用此程序，提示以下错误信息
貌似保存为html也存在类似问题
```
File "fanqienovel-downloader-v1.1.4.py", line 693, in <module>
File "fanqienovel-downloader-v1.1.4.py", line 545, in book2down
File "fanqienovel-downloader-v1.1.4.py", line 237, in down_book_epub
AttributeError: 'tuple' object has no attribute 'replace'
[13088] Failed to execute script 'fanqienovel-downloader-v1.1.4' due to unhandled exception!

```
以下是具体操作演示：
![屏幕截图 2024-09-04 151608](https://github.com/user-attachments/assets/6da0b63b-4781-4702-9b96-5872148447a2)

**Comment by qxqycb** [comment]
字符串类型但被错误地赋值为元组，所以报错

**Comment by XiaoHuangJiYa** [comment]
> 字符串类型但被错误地赋值为元组，所以报错

抱歉，我也不是很懂计算机，不知道这是不是我的电脑环境问题，请教大佬，我应该做些什么才能解决这个问题

**Comment by qxqycb** [comment]
应该是程序的问题，你先删除本程序所有有关文件，再重新下载使用，看看有没有问题

**Comment by XiaoHuangJiYa** [comment]
> 应该是程序的问题，你先删除本程序所有有关文件，再重新下载使用，看看有没有问题

收到，我明天折腾一下，如果还是有问题，我再跟大佬反馈

**Comment by qxqycb** [comment]
感谢支持😀

**Comment by XiaoHuangJiYa** [comment]
> 感谢支持😀

![屏幕截图 2024-09-07 002735](https://github.com/user-attachments/assets/7669e5c5-7cbc-4c74-80f7-46f7bbe83682)

两次下载的哈希值是一致的，试用新下载的软件，设置之后依然闪退，貌似保存成html后也有类似问题

**Comment by qxqycb** [comment]
收到，下午就修改

**Comment by qxqycb** [comment]
已修改，请下载最新版v1.1.5程序

**Comment by qxqycb** [comment]
最后，感谢你的反馈
