### ISSUE TITLE
关于保存成epub的一点建议

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#36]
版本：fanqienovel-downloader v1.1.5
保存格式：epub
问题一：
设置了段首2个占位符“　”，但使用epub阅读器（calibre，koodo等都试过）打开后，没有首行缩进的效果。
![epub-1](https://github.com/user-attachments/assets/5e29d17b-ff15-45c8-8a16-34e88fdf7868)

问题二：
如果可能，生成的epub能否自动添加图书封面呢？那样就完美了，哈！

感谢！

**Comment by Suyan-Jian** [comment]
都用calibre了，那就先下载带缩进的txt格式的，calibre编辑元数据把番茄的图书封面和作者名加上，然后转换成epub或者其他格式。在转换的时候还可以顺便生成目录啥的，自己弄也不麻烦，就不用麻烦这里的作者了~他们很忙，对这个项目来说添加这个功能也很麻烦

**Comment by qxqycb** [comment]
没事，做完了

**Comment by qxqycb** [comment]
明天就发

**Comment by doggybread** [comment]
> 没事，做完了

精益求精，给你们点赞！
PS：正如前面的书友所说，所提建议只是“锦上添花”，用其它方法也可以实现，就算不处理也无大碍。「能够正常下载、更新」才是本项目的核心功能，只要核心功能正常，其他一切皆可为浮云，无非是让“收藏小说数量众多的书虫”能偷个懒罢了（笑）。

**Comment by qxqycb** [comment]
> > 没事，做完了
> 
> 精益求精，给你们点赞！ PS：正如前面的书友所说，所提建议只是“锦上添花”，用其它方法也可以实现，就算不处理也无大碍。「能够正常下载、更新」才是本项目的核心功能，只要核心功能正常，其他一切皆可为浮云，无非是让“收藏小说数量众多的书虫”能偷个懒罢了（笑）。

哈哈哈

**Comment by qxqycb** [comment]
更新完成，请下载最新程序
