### ISSUE TITLE
下载出现的问题&排版

### ISSUE THREAD

**Issue by baby1128** [ying-ck/fanqienovel-downloader#4]
首先，感谢作者提供的工具，真的很棒！
但是使用过程发现了有出现的问题。
下载时候，偶尔会出现这样这样的代码（如图）
![01](https://github.com/user-attachments/assets/75f8003f-cdb9-4c7d-b7e2-12ab0a1952d1)
<p class="   ">
就是这一串，前面另外一本书也出现过类似的。
这是我下载时候遇到的问题。
另外，下载生成的排版，可否正文内容，开头空2字符？

![02](https://github.com/user-attachments/assets/6d85fef6-ba1b-4688-9ff4-a14076674d20)
这是目前下载下来的效果。

![03](https://github.com/user-attachments/assets/eef4f5f6-704f-4ca7-ae20-387297445443)
想要下载下来之后，直接像这样排版效果。
最后，祝学业进步！

**Comment by ying-ck** [comment]
新的功能已经在v1.0.4了，正文中的代码也使用xpath方式清除了。但如此图片的链接也同样清除了

**Comment by baby1128** [comment]
谢谢~~ღ( ´･ᴗ･` )比心

**Comment by LiuJiewenTT** [comment]
> 新的功能已经在v1.0.4了，正文中的代码也使用xpath方式清除了。但如此图片的链接也同样清除了

为啥不干脆输出成html？（好奇）

**Comment by ying-ck** [comment]
> > 新的功能已经在v1.0.4了，正文中的代码也使用xpath方式清除了。但如此图片的链接也同样清除了
> 
> 为啥不干脆输出成html？（好奇）

那样为什么不在官网上直接看呢?

**Comment by LiuJiewenTT** [comment]
> > > 新的功能已经在v1.0.4了，正文中的代码也使用xpath方式清除了。但如此图片的链接也同样清除了
> > 
> > 
> > 为啥不干脆输出成html？（好奇）
> 
> 那样为什么不在官网上直接看呢?

因为想离线啊，这样官方下架了就影响不到了

**Comment by qxqycb** [comment]
@LiuJiewenTT 哥，
HTML（超文本标记语言——HyperText Markup Language）是构成 Web 世界的一砖一瓦。它定义了网页内容的含义和结构。除 HTML 以外的其他技术则通常用来描述一个网页的表现与展示效果（如 [CSS](https://developer.mozilla.org/zh-CN/docs/Web/CSS)），或功能与行为（如 [JavaScript](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript)）
它长这样：
<html>
<body>

<!doctype html><html lang="en-US" prefix="og: https://ogp.me/ns#"><head><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="icon" href="/favicon-48x48.cbbd161b.png"/><link rel="apple-touch-icon" href="/apple-touch-icon.6803c6f0.png"/><meta name="theme-color" content="#ffffff"/><link rel="manifest" href="/manifest.56b1cedc.json"/><link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="MDN Web Docs"/><title>HTML（超文本标记语言） \| MDN</title><link rel="alternate" title="HTML: HyperText Markup Language" href="https://developer.mozilla.org/en-US/docs/Web/HTML" hreflang="en"/><link rel="alternate" title="HTML: Lenguaje de etiquetas de hipertexto" href="https://developer.mozilla.org/es/docs/Web/HTML" hreflang="es"/><link rel="alternate" title="HTML (HyperText Markup Language)" href="https://developer.mozilla.org/fr/docs/Web/HTML" hreflang="fr"/><link rel="alternate" title="HTML: ハイパーテキストマークアップ言語" href="https://developer.mozilla.org/ja/docs/Web/HTML" hreflang="ja"/><link rel="alternate" title="HTML: Hypertext Markup Language" href="https://developer.mozilla.org/ko/docs/Web/HTML" hreflang="ko"/><link rel="alternate" title="HTML: Linguagem de Marcação de Hipertexto" href="https://developer.mozilla.org/pt-BR/docs/Web/HTML" hreflang="pt"/><link rel="alternate" title="HTML" href="https://developer.mozilla.org/ru/docs/Web/HTML" hreflang="ru"/><link rel="alternate" title="HTML：超文本標記語言" href="https://developer.mozilla.org/zh-TW/docs/Web/HTML" hreflang="zh-Hant"/><link rel="alternate" title="HTML（超文本标记语言）" href="https://developer.mozilla.org/zh-CN/docs/Web/HTML" hreflang="zh"/><link rel="preload" as="font" type="font/woff2" href="/static/media/Inter.var.c2fe3cb2b7c746f7966a.woff2" crossorigin><link rel="alternate" type="application/rss+xml" title="MDN Blog RSS Feed" href="https://developer.mozilla.org/en-US/blog/rss.xml" hreflang="en" /><meta name="description" content="HTML（超文本标记语言——HyperText Markup Language）是构成 Web 世界的一砖一瓦。它定义了网页内容的含义和结构。除 HTML 以外的其他技术则通常用来描述一个网页的表现与展示效果（如 CSS），或功能与行为（如 JavaScript）。"/><meta property="og:url" content="https://developer.mozilla.org/zh-CN/docs/Web/HTML"/><meta property="og:title" content="HTML（超文本标记语言） \| MDN"/><meta property="og:type" content="website"/><meta property="og:locale" content="zh_CN"/><meta property="og:description" content="HTML（超文本标记语言——HyperText Markup Language）是构成 Web 世界的一砖一瓦。它定义了网页内容的含义和结构。除 HTML 以外的其他技术则通常用来描述一个网页的表现与展示效果（如 CSS），或功能与行为（如 JavaScript）。"/><meta property="og:image" content="https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png"/><meta property="og:image:type" content="image/png"/><meta property="og:image:height" content="1080"/><meta property="og:image:width" content="1920"/><meta property="og:image:alt" content="The MDN Web Docs logo, featuring a 
跟shi一样，这也读不了啊

**Comment by qxqycb** [comment]
<html>
<body>

<li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding">多媒体与嵌入概述</a></li>
--
  | <li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML">HTML 中的图片</a></li>
  | <li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content">视频和音频内容</a></li>
  | <li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies">从 object 到 iframe——其他嵌入技术</a></li>
  | <li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web">为 web 新增矢量图</a></li>
  | <li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images">响应式图片</a></li>
  | <li><a href="/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page">测验：Mozilla 醒目页面</a></li>


</body>
</html><li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding)">多媒体与嵌入概述</a></li>
        <li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML)">HTML 中的图片</a></li>
        <li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content)">视频和音频内容</a></li>
        <li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies)">从 object 到 iframe——其他嵌入技术</a></li>
        <li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web)">为 web 新增矢量图</a></li>
        <li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)">响应式图片</a></li>
        <li><a href="[/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page)">测验：Mozilla 醒目页面</a></li>

**Comment by qxqycb** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>下拉列表示例</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .dropdown {
            position: relative;
            display: inline-block;
        }
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }
        .dropdown-content a:hover {background-color: #f1f1f1}
        .dropdown:hover .dropdown-content {display: block;}
        .dropdown:hover .dropbtn {background-color: #3e8e41;}
    </style>
</head>
<body>

<h2>以下是我的一些项目:</h2>
<div class="dropdown">
  <button class="dropbtn">项目列表</button>
  <div class="dropdown-content">
    <a href="#">项目1</a>
    <a href="#">项目2</a>
    <a href="#">项目3</a>
    <a href="#">项目4</a>
  </div>
</div>

</body>
</html>

**Comment by qxqycb** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>下拉列表示例</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .dropdown {
            position: relative;
            display: inline-block;
        }
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;

**Comment by qxqycb** [comment]
跟shi一样，看不了

**Comment by LiuJiewenTT** [comment]
> 跟shi一样，看不了

只是觉得能当备选，又不是一定要用TXT才能阅读，哪个设备没有浏览器？直接让浏览器渲染不香吗？干嘛要看HTML代码

**Comment by qxqycb** [comment]
是的，只能当备选
但是我们学校机房就没有浏览器，U盘又被锁了

**Comment by qxqycb** [comment]
2345浏览器，卡死的那种，却各种各样的dll

**Comment by qxqycb** [comment]
2345浏览器，卡死的那种，缺各种各样的dll

**Comment by LiuJiewenTT** [comment]
> 2345浏览器，卡死的那种，缺各种各样的dll

但是你也不能插U盘，那你想怎么办？勉强把这软件下了然后下半天小说吗？不如下一个Chrome试试，不需魔法

**Comment by qxqycb** [comment]
老师把网关了

**Comment by qxqycb** [comment]
服了

**Comment by ying-ck** [comment]
哈哈
