### ISSUE TITLE
1.1.5版本闪退

### ISSUE THREAD

**Issue by buding9527** [ying-ck/fanqienovel-downloader#40]
![崩溃截图](https://github.com/user-attachments/assets/18dd759a-4670-47e8-bb8b-e8c5439bb51f)
打开如图所示 然后消失

**Comment by buding9527** [comment]
现在访问https://fanqienovel.com/page/加id 的网页直接空白 是什么原因导致的啊
![image](https://github.com/user-attachments/assets/b03ad810-6fee-493e-827c-a6eccce1ddb9)

**Comment by sstzer** [comment]
触发番茄的反爬虫了吧应该是

**Comment by qinxitong** [comment]
下载小说下的太多了触发番茄黑名单了应该是，我之前这样过，插拔路由器重新获取IP试试

**Comment by buding9527** [comment]
> 触发番茄的反爬虫了吧应该是

一本小说都没下载完

**Comment by buding9527** [comment]
> 下载小说下的太多了触发番茄黑名单了应该是，我之前这样过，插拔路由器重新获取IP试试

我一本小说都没下载完，然后一直卡在那里  我关闭之后就这样了，重启路由器，重启光猫都没用，我到现在都访问不了，离谱
