### ISSUE TITLE
一直获取cookie

### ISSUE THREAD

**Issue by mrzrh-awc** [ying-ck/fanqienovel-downloader#41]
进不了下载的咋搞，一直获取coolie

**Comment by mrzrh-awc** [comment]
![Uploading 微信图片_20240911151923.png…]()

**Comment by Aizmina** [comment]
我也出现了这个问题，挂了好长时间都不成功

**Comment by limmandyy** [comment]
我也有同样问题，还以为是我的电脑有问题呢，结果是程序有问题

**Comment by Aizmina** [comment]
> 我也有同样问题，还以为是我的电脑有问题呢，结果是程序有问题

找到一个油猴脚本可以正常使用

**Comment by buding9527** [comment]
> > 我也有同样的问题，还以为是我的电脑有问题呢，结果是程序有问题
> 
> 找到一个油猴脚本可以正常使用

能发一下吗

**Comment by qxqycb** [comment]
发一下

**Comment by ying-ck** [comment]
已解决
