### ISSUE TITLE
1.1.5版本获取cookie不成功

### ISSUE THREAD

**Issue by nandehututu** [ying-ck/fanqienovel-downloader#42]
get_cookie里的down_text里的res = req.get('https://fanqienovel.com/api/reader/full?itemId=' + str(it), headers=headers2)
返回的是200，但是包里无内容

**Comment by nandehututu** [comment]
挂了一个小时还是无内容，是链接不行了还是ip被封禁了？

**Comment by ying-ck** [comment]
已解决
