### ISSUE TITLE
关于API失效的问题

### ISSUE THREAD

**Issue by qxqycb** [ying-ck/fanqienovel-downloader#46]
由于开学的原因，作者无法及时回复，敬请谅解
fanqienovel downloader由于API失效无法使用，现在有几个选择：
1.等待至API恢复使用
2.换用新的API
3.使用新的下载方法，目前没有
4.项目存档

**Comment by MachMY** [comment]
番茄好像是每半年换一次API，这次未有大佬逆向出API

不知以下链接的讨论区能不能帮到您
https://greasyfork.org/zh-CN/scripts/476688-%E5%8F%AF%E8%83%BD%E5%A4%B1%E6%95%88-%E7%95%AA%E8%8C%84%E5%85%A8%E6%96%87%E5%9C%A8%E7%BA%BF%E5%85%8D%E8%B4%B9%E8%AF%BB/discussions/259117
https://greasyfork.org/zh-CN/scripts/476688-%E5%8F%AF%E8%83%BD%E5%A4%B1%E6%95%88-%E7%95%AA%E8%8C%84%E5%85%A8%E6%96%87%E5%9C%A8%E7%BA%BF%E5%85%8D%E8%B4%B9%E8%AF%BB/discussions/241904
https://greasyfork.org/zh-CN/scripts/476688-%E5%8F%AF%E8%83%BD%E5%A4%B1%E6%95%88-%E7%95%AA%E8%8C%84%E5%85%A8%E6%96%87%E5%9C%A8%E7%BA%BF%E5%85%8D%E8%B4%B9%E8%AF%BB/discussions/238936

**Comment by c1rcle-xy** [comment]
吾爱破解也有个大佬写了个下载器，有源码大佬可以看看这个
https://www.52pojie.cn/thread-1958479-1-1.html

**Comment by MachMY** [comment]
> 吾爱破解也有个大佬写了个下载器，有源码大佬可以看看这个 https://www.52pojie.cn/thread-1958479-1-1.html

大大介意帮忙转存到UC盘或百度盘吗？外国人用不了蓝奏云 XD

**Comment by qxqycb** [comment]
> > 吾爱破解也有个大佬写了个下载器，有源码大佬可以看看这个 https://www.52pojie.cn/thread-1958479-1-1.html
> 
> 大大介意帮忙转存到UC盘或百度盘吗？外国人用不了蓝奏云 XD

哪一个？源代码还是文件？

**Comment by qxqycb** [comment]
通过百度网盘分享的文件：番茄七猫小说下载…
链接:https://pan.baidu.com/s/1s6jNleaamaXDO_iZB5ISVw 
提取码:s8bz
复制这段内容打开「百度网盘APP 即可获取」

**Comment by MachMY** [comment]
> 通过百度网盘分享的文件：番茄七猫小说下载… 链接:[https://pan.baidu.com/s/1s6jNleaamaXDO_iZB5ISVw ](https://pan.baidu.com/s/1s6jNleaamaXDO_iZB5ISVw%C2%A0) 提取码:s8bz 复制这段内容打开「百度网盘APP 即可获取」

大大，这是已失效的1.0.4版本 XD

**Comment by dadizhanshen** [comment]
> 吾爱破解也有个大佬写了个下载器，有源码大佬可以看看这个 https://www.52pojie.cn/thread-1958479-1-1.html

吾爱破解的会有乱码章节

**Comment by ying-ck** [comment]
现在下载小说已经不受影响了，但是搜索相关还是需要等有时间再做。

**Comment by buding9527** [comment]
> 现在下载小说已经没有了，但是搜索相关的还是需要等有时间再做。

谢谢大佬 辛苦了 能添加一个下载下架小说的功能吗 能获取到下架小说的bookid 但是没法下载

**Comment by dadizhanshen** [comment]
> 现在下载小说已经不受影响了，但是搜索相关还是需要等有时间再做。

感谢大佬

**Comment by qxqycb** [comment]
> > 现在下载小说已经没有了，但是搜索相关的还是需要等有时间再做。
> 
> 谢谢大佬 辛苦了 能添加一个下载下架小说的功能吗 能获取到下架小说的bookid 但是没法下载

目前还不行，是获取到下架小说的bookid 但是没法下载，番茄的服务器里面已经没有了
