### ISSUE TITLE
番茄小说下载器能否参考这个下载脚本，确保能够下载到内容

### ISSUE THREAD

**Issue by bjr616** [ying-ck/fanqienovel-downloader#47]
1、使用这个小说下载器，可以下载番茄的小说，但是缺好多的字符，如何补全？
[novelDownloader3.user.js](https://github.com/dodying/UserJs/blob/master/novel/novelDownloader/novelDownloader3.user.js

2、番茄小说下载器能否参考这个下载脚本，确保能够下载到内容。

**Comment by qxqycb** [comment]
回答：
1.可以用一下我新编的[程序](https://github.com/qxqycb/Character-transcoding)
2.不能，脚本使用的浏览器本身为载体，而下载器是以电脑为载体

**Comment by bjr616** [comment]
使用脚本下载后的TXT文件（缺字符的），在使用您新编的程序后，生成的文件中字符还是与番茄小说下载器直接下载的文件不一样的地方。
如：四->西  已->己 直->首  等，如何才能完全对应？
![无标题](https://github.com/user-attachments/assets/101dc435-9cff-4338-b486-8a69ffa5f87a)

**Comment by bjr616** [comment]
能提供一下源代码，我自己修改一下对应的错别字吗？谢谢！

**Comment by qxqycb** [comment]
> 使用脚本下载后的TXT文件（缺字符的），在使用您新编的程序后，生成的文件中字符还是与番茄小说下载器直接下载的文件不一样的地方。 如：四->西 已->己 直->首 等，如何才能完全对应？ ![无标题](https://private-user-images.githubusercontent.com/178962996/367595569-101dc435-9cff-4338-b486-8a69ffa5f87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjA3OTMsIm5iZiI6MTcyNjQyMDQ5MywicGF0aCI6Ii8xNzg5NjI5OTYvMzY3NTk1NTY5LTEwMWRjNDM1LTljZmYtNDMzOC1iNDg2LThhNjlmZmE1Zjg3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNzE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGRkNmQzZWY2MWQ1ZWJlY2JhNDI0MDc2YzZmMzFhNDA4MGY5Y2Q5YzM4NDFiZmY3YmRkNzhkOWY3ODU2OWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._JvxKIohCjpaUpowIY_bVdasDaldAR53tKRGxx0_ZBM)

哈哈哈，这个不是错误，是作者自己改的，因为避讳“死”、“直”等敏感内容

**Comment by qxqycb** [comment]
另外：源代码已添加

**Comment by bjr616** [comment]
谢谢作者了

**Comment by bjr616** [comment]
源代码不对啊，不是修改字符的。好像是分割章节的。能不能重新上传一下，谢谢了

**Comment by bjr616** [comment]
> > 使用脚本下载后的TXT文件（缺字符的），在使用您新编的程序后，生成的文件中字符还是与番茄小说下载器直接下载的文件不一样的地方。 如：四->西 已->己 直->首 等，如何才能完全对应？ ![无标题](https://private-user-images.githubusercontent.com/178962996/367595569-101dc435-9cff-4338-b486-8a69ffa5f87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjA3OTMsIm5iZiI6MTcyNjQyMDQ5MywicGF0aCI6Ii8xNzg5NjI5OTYvMzY3NTk1NTY5LTEwMWRjNDM1LTljZmYtNDMzOC1iNDg2LThhNjlmZmE1Zjg3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNzE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGRkNmQzZWY2MWQ1ZWJlY2JhNDI0MDc2YzZmMzFhNDA4MGY5Y2Q5YzM4NDFiZmY3YmRkNzhkOWY3ODU2OWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._JvxKIohCjpaUpowIY_bVdasDaldAR53tKRGxx0_ZBM)
> 
> 哈哈哈，这个不是错误，是作者自己改的，因为避讳“死”、“直”等敏感内容

作者自己改的？不理解。
使用咱们的番茄下载器下载的文本内容是对的。使用浏览器脚本下载的内容是缺字符的，在使用番茄小说字符乱码转换器后才有错误的，应该是这个转换器的问题吧？

**Comment by bjr616** [comment]
> 回答： 1.可以用一下我新编的[程序](https://github.com/qxqycb/Character-transcoding) 2.不能，脚本使用的浏览器本身为载体，而下载器是以电脑为载体

是的，这是两种不同的下载方式。不过使用浏览器用过脚本下载的速度好像快一些。

**Comment by qxqycb** [comment]
抱歉，发错了

**Comment by qxqycb** [comment]
下午发，中午要去过中秋节，回不了家

**Comment by qxqycb** [comment]
> > > 使用脚本下载后的TXT文件（缺字符的），在使用您新编的程序后，生成的文件中字符还是与番茄小说下载器直接下载的文件不一样的地方。 如：四->西 已->己 直->首 等，如何才能完全对应？ ![无标题](https://private-user-images.githubusercontent.com/178962996/367595569-101dc435-9cff-4338-b486-8a69ffa5f87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjA3OTMsIm5iZiI6MTcyNjQyMDQ5MywicGF0aCI6Ii8xNzg5NjI5OTYvMzY3NTk1NTY5LTEwMWRjNDM1LTljZmYtNDMzOC1iNDg2LThhNjlmZmE1Zjg3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNzE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGRkNmQzZWY2MWQ1ZWJlY2JhNDI0MDc2YzZmMzFhNDA4MGY5Y2Q5YzM4NDFiZmY3YmRkNzhkOWY3ODU2OWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._JvxKIohCjpaUpowIY_bVdasDaldAR53tKRGxx0_ZBM)
> > 
> > 哈哈哈，这个不是错误，是作者自己改的，因为避讳“死”、“直”等敏感内容
> 
> 作者自己改的？不理解。
> 使用咱们的番茄下载器下载的文本内容是对的。使用浏览器脚本下载的内容是缺字符的，在使用番茄小说字符乱码转换器后才有错误的，应该是这个转换器的问题吧？

真的不是，我有番茄的VIP，看了很多文章，有很多都有这样的错字，一般是好过审

**Comment by bjr616** [comment]
> 下午发，中午要去过中秋节，回不了家

中秋节快乐！

**Comment by bjr616** [comment]
期待您的源代码，呵呵

**Comment by qxqycb** [comment]
发了
