### ISSUE TITLE
超赞！强力点赞！顺带抓个小Bug

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#48]
首先感谢如此NB的更新！

趁热体验了以下，下载后直接获得Epub电子书，带封面和目录，灰常了不起！

已经在Calibre 7.12和 Koodo Reader 1.6.9 中测试通过，正常导入阅读，没有问题。

只是发现一个很小的问题，不处理问题也不大的那种，在此恬不知耻地提出，望作者海涵。

目录变成了多层结构，感觉像是生成目录时重复了，具体如下图所示：

![目录问题2](https://github.com/user-attachments/assets/b2a59a23-b94a-4009-b84b-5b789d538640)

![目录问题](https://github.com/user-attachments/assets/9896e7f3-b782-4e96-9851-77e68f37cabf)

**Comment by qxqycb** [comment]
感谢反馈，今天还将添加备份功能

**Comment by Nathalie-Annis** [comment]
作者名能顺便加上吗，谢谢啦

**Comment by qxqycb** [comment]
OK

**Comment by qxqycb** [comment]
这样行不行？
toc.append(chapter_title, [chapter])
        book.spine.append(chapter)
    pbar.update(1)

book.toc = toc
book.add_item(epub.EpubNcx())

**Comment by Nathalie-Annis** [comment]
toc.append((epub.Section(chapter_title), [chapter]))问题应该在这里，epub.Section(chapter_title) 表示创建了一个“章节组”，并将 chapter 作为该组下的子项，不用这个应该就没问题

**Comment by qxqycb** [comment]
已更新，请下载最新程序v1.1.8
