### ISSUE TITLE
备份功能需要管理员权限

### ISSUE THREAD

**Issue by Nathalie-Annis** [ying-ck/fanqienovel-downloader#50]
<img width="861" alt="屏幕截图 2024-09-16 172956" src="https://github.com/user-attachments/assets/21545aaa-2a5a-4a0e-8e66-08d3e8211afa">
只有用管理员身份运行的时候才能备份
BTW还没有太明白备份的作用

**Comment by qxqycb** [comment]
以管理员身份运行程序试试

**Comment by Nathalie-Annis** [comment]
嗯嗯，这样是可以的，那就设置程序运行时请求管理员权限吧，要不然忘了管理员身份打开就容易异常退出了

**Comment by Nathalie-Annis** [comment]
嗯嗯，这样是可以的，那就设置程序启动时请求管理员权限吧，要不然忘了管理员身份打开就容易异常退出了

**Comment by qxqycb** [comment]
> 
> <img width="861" alt="屏幕截图 2024-09-16 172956" src="https://github.com/user-attachments/assets/21545aaa-2a5a-4a0e-8e66-08d3e8211afa">
> 只有用管理员身份运行的时候才能备份
> BTW还没有太明白备份的作用
> 

备份功能主要是防止程序下载时出错将所有文件都覆盖了，还有一个功能：更新了更新的程序（例如：v1.1.9）就可以用原来的配置，不用再次修改
