### ISSUE TITLE
更新时遇到的奇怪问题

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#52]
用上了最新的1.1.8版本。
香！

就是在更新时遇到了奇怪问题：
每一次更新，都会从第一章开始重新下载~
我新下载了两部小说，然后立刻更新，结果也是把刚下载好的内容再下载一遍。
![更新问题](https://github.com/user-attachments/assets/18ce2ead-ea84-42fc-8f18-a7255943baf8)

BTW：我查看了一下“data\bookstore”中的内容，发现json文件中只有章节的名称，没有正文内容，不只是不是因为这个原因导致每次都要重新下载。

**Comment by ygdsad** [comment]
闪退

**Comment by qxqycb** [comment]
> 闪退
> 

详细说一下报错代码

**Comment by qxqycb** [comment]
已修复，请下载最新程序
