### ISSUE TITLE
数据迁移时遇到的问题

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#53]
我打算把之前1.1.6下载的小说（包括record以及bookstore中的内容）更新到1.1.8版本中，于是做了以下测试。

1、将一部小说位于booksotre中的json文件，复制到1.1.8程序相对应的bookstore中。
2、将该小说的ID写入1.1.8的record.json文件
3、启动1.1.8，执行更新

结果如下：
1、成功更新了最新两个章节内容，但章节内容没有存入bookstore下的json文件中。
2、成功生成了带封面和目录的Epub文件，但该EPub中仅包含最新更新的两章内容，之前的章节没有写入，如下图所示。

![更新问题2](https://github.com/user-attachments/assets/ac45e9a5-f2df-4380-a596-0c9d53357265)

是否1.1.8不认识之前的json文件了？所有小说都需重新下载？

PS：感谢作者的辛勤付出！为你们点赞！

**Comment by qxqycb** [comment]
已修复，请下载最新程序
