### ISSUE TITLE
1.1.9更新时还是报错

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#54]
作者辛苦了。
1.1.9 程序刚才试验了一下，步骤如下：

1、全新目录，bookstore和record.json都是清空状态
2、全新下载一本小说，输入ID：7383141098492808216
3、下载过程十分流畅，生成的EPUB也非常完美，赞。
4、关闭程序重新进入，选择1更新，结果报错，内容如下：

![更新错误](https://github.com/user-attachments/assets/684d594c-2a89-4a7c-84a8-a384ba42da79)

**Comment by doggybread** [comment]
补充一下，如果下载格式为单个TXT文件，则更新没有问题。设置成EPUB才会出现上述错误。

**Comment by qxqycb** [comment]
最新版已修改，明天发
