### ISSUE TITLE
批量下载后出错

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#55]
版本：1.1.9
问题描述：批量下载完成后，程序退出
下载参数：epub格式
![批量下载错误](https://github.com/user-attachments/assets/07544fcb-59a4-4864-9ea1-98491c15df47)

**Comment by qxqycb** [comment]
报错后能程序正常保存文件了吗吗？

**Comment by qxqycb** [comment]
最新版已修改
