### ISSUE TITLE
json遇到问题

### ISSUE THREAD

**Issue by LiuJiewenTT** [ying-ck/fanqienovel-downloader#6]
下载此书时出错：https://fanqienovel.com/page/7286403917603146814

如图：
![图片](https://github.com/user-attachments/assets/9e3ecbd9-ce6c-483e-abe1-c27a9cdb7d5e)

**Comment by ying-ck** [comment]
> 下载此书时出错：https://fanqienovel.com/page/7286403917603146814
> 
> 如图：
> ![图片](https://github.com/user-attachments/assets/9e3ecbd9-ce6c-483e-abe1-c27a9cdb7d5e)
> 

每次都是这样吗

**Comment by ying-ck** [comment]
刚刚改了一下代码，你可以试试看，增加了一些容错。我就先不打包了。

**Comment by LiuJiewenTT** [comment]
好像可以了，继续下载完了。就是你最新的commit把indent破坏了
