### ISSUE TITLE
番茄短故事没有内容

### ISSUE THREAD

**Issue by Ruobinbin** [ying-ck/fanqienovel-downloader#61]
用于下载番茄短故事获取不到内容

以下是txt文件内容

{
小说名：末世降临，白眼狼家人我不要了
作者：勤奋且努力
内容简介：末世降临，白眼狼家人我不要了

末世降临，白眼狼家人我不要了
}

**Comment by Ruobinbin** [comment]
bookid
7417275703697080856

**Comment by bjr616** [comment]
> bookid 7417275703697080856

确实是，这个小说只有一章，但无法内容为空

**Comment by Ruobinbin** [comment]
短故事好像都是空的

**Comment by qxqycb** [comment]
短故事用的XPath和其它小说的不一样，已修复，请下载最新版本
