### ISSUE TITLE
1.1.14选择更新选项后闪退一直打不开

### ISSUE THREAD

**Issue by clx113** [ying-ck/fanqienovel-downloader#64]
![微信图片_20241021035622](https://github.com/user-attachments/assets/23bc3061-60b3-4e45-9ac7-62243f21b45f)
之前正常使用 在输入1并确定后一直闪退 打开到这一步就直接闪退 删除重下也没有用 想问一下有解决方案吗？

**Comment by qxqycb** [comment]
我打开怎么没有问题呢？
