### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by sstzer** [ying-ck/fanqienovel-downloader#67]
1. 功能越堆越多，文件越来越大，最好还是给拆拆吧
2. 不同下载格式可以抽象出个基类然后简化开发

**Comment by qxqycb** [comment]
确实，太多的下载格式有一点复杂，不好维护

**Comment by sstzer** [comment]
> 确实，太多的下载格式有一点复杂，不好维护

我觉得我可以先把1给搞了，改完提个pr（但是可能得过两天），或者一点点拆，边拆边merge方便随时加新功能，你来定，然后重构的时候2就是顺手的事

**Comment by sstzer** [comment]
> 确实，太多的下载格式有一点复杂，不好维护

还有一件事，main和main2有啥区别，还有那个ref是加网页之前的版本不用管了是吧

**Comment by qxqycb** [comment]
main2.py针对python3.8及以下的string语句不能使用\，main.py反之
