### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by heyuquan1990** [ying-ck/fanqienovel-downloader#68]
Traceback (most recent call last):
  File "/home/heyuquan/fanqienovel-downloader/src/server.py", line 6, in <module>
    from main import NovelDownloader, Config, SaveMode
  File "/home/heyuquan/fanqienovel-downloader/src/main.py", line 479
    f.write(f'{chapter_content.replace("\n", fg)}\n')
                                                    ^
SyntaxError: f-string expression part cannot include a backslash

**Comment by qxqycb** [comment]
> Traceback (most recent call last):
>   File "/home/heyuquan/fanqienovel-downloader/src/server.py", line 6, in <module>
>     from main import NovelDownloader, Config, SaveMode
>   File "/home/heyuquan/fanqienovel-downloader/src/main.py", line 479
>     f.write(f'{chapter_content.replace("\n", fg)}\n')
>                                                     ^
> SyntaxError: f-string expression part cannot include a backslash

你python用的什么版本？

**Comment by qxqycb** [comment]
3.8及以下用main2.py，不是main.py

**Comment by heyuquan1990** [comment]
> > Traceback (most recent call last):
> >   File "/home/heyuquan/fanqienovel-downloader/src/server.py", line 6, in <module>
> >     from main import NovelDownloader, Config, SaveMode
> >   File "/home/heyuquan/fanqienovel-downloader/src/main.py", line 479
> >     f.write(f'{chapter_content.replace("\n", fg)}\n')
> >                                                     ^
> > SyntaxError: f-string expression part cannot include a backslash
> 
> 你python用的什么版本？
> 

3.8，后来发现要使用 main2.py，现在没问题了
