### ISSUE TITLE
段首空格设置后无效果

### ISSUE THREAD

**Issue by doggybread** [ying-ck/fanqienovel-downloader#7]
版本：fanqienovel-downloader-v1.0.5.exe
系统：Win10,64位
问题描述：
1、执行fanqienovel-downloader-v1.0.5.exe，选择“2”，输入“2”后完成段首空格设置。
2、输入小说ID：7350319588740959256，全新下载一本小说。
3、下载完成的TXT文件，段首仍然没有空格。

疑问：选择2设置后，是否是输入空格数进行设置？还是直接输入空格？我不管怎么设置config.json中内容都没有改变。都是{"kg": 0}
建议：界面上如果能有清晰提示就更好了，感谢！

BTW：是否有考虑通过命令行启动下载程序？比如指令：“fanqienovel-downloader-v1.0.5.exe -gx ” 可以在后台开启更新程序，这样就有可能通过系统计划定时执行更新程序了，如果能考虑一下就太赞了！

最后多说一句，这个工具真的很棒！给作者一个大大的赞！感谢！

**Comment by ying-ck** [comment]
空格的问题我记得之前测试应该是好的呀？
你可以直接更改json文件为{"kg":2}来进行尝试，晚上有电脑时我再看看。

**Comment by doggybread** [comment]
哇，作者回复超快滴！
试了一下，修改json文件确实有效果，空格出现了！
但能否提个小建议，段首缩进空格能否改成“全角空格”？或者设置一个半角和全角开关。毕竟是下载中文小说，全角空格在显示上更友好些。
再次感谢！

**Comment by ying-ck** [comment]
谢谢支持!
晚上尝试改个空格试试。

**Comment by ying-ck** [comment]
v1.0.6增加了可以使用命令行更新专用程序，可以在release里找到。
