### ISSUE TITLE
web版改进方向

### ISSUE THREAD

**Issue by qxqycb** [ying-ck/fanqienovel-downloader#70]
1.Web版添加在线阅读功能，注意根路由配置正确，最好加一个reader.html
2.epub下载格式中没有换行符
有想法的可以git项目zip，自己改一下，提个pr

**Comment by Nathalie-Annis** [comment]
哈哈，其实这个epub换行我一个月前就做了，加了epub的css和分卷，支持二级目录显示，为了kindle推书方便还添加了根据章节数量拆分生成多个epub书籍的功能，不过因为是自用的，程序的主循环也做了一些更改，可能不好pr了

**Comment by Nathalie-Annis** [comment]
哈哈，其实这个epub换行我一个月前就做了，加了epub的css，爬了书籍的卷名，支持二级目录显示，为了kindle推书方便还添加了根据章节数量拆分生成多个epub书籍的功能，不过因为是自用的，程序的主循环也做了一些更改，可能不好pr了
