### ISSUE TITLE
WEB端和exe版本的bug

### ISSUE THREAD

**Issue by baiheyyds** [ying-ck/fanqienovel-downloader#72]
运行环境：WIN10
python版本：v3.13

**遇到的问题：**
运行exe版本时，有时候能正常下载整本书，有时候下载的书籍会章节内容缺失（怀疑跟线程数有关，实测6线程基本都能完整下载，8线程有时候会出现后面下载空章节的情况（70%概率），只下载一个章节名，内容都没了），但是很奇怪的是WEB版本线程调到16都能完整下载内容。只是章节排序都是乱的。

因为章节排序问题，所以WEB端几乎不能用，不知道是不是就我这样，我下的每一本书都是章节排序都是乱的，而整合版（exe版本）章节就很正常，因为WEB端不需要频繁开关代理，可以直接走直连，如果能解决章节乱序这个问题就yyds了，希望大佬有时间可以排查一下

**Comment by qxqycb** [comment]
我这边没有空章节的问题啊？
还有章节乱序已修复
