### ISSUE TITLE
web 版保存为 EPUB 格式没有段落

### ISSUE THREAD

**Issue by heyuquan1990** [ying-ck/fanqienovel-downloader#76]
web 版保存为 EPUB 格式没有段落，而且每次更新都会从第一章开始重新下载，TXT 格式正常，其他格式没使用过![Screenshot_2024-11-07-20-18-28-181_com.dragon.read.jpg](https://github.com/user-attachments/assets/22028752-45bf-4989-b928-2b0977bbc84e)

**Comment by qxqycb** [comment]
已修复
