### ISSUE TITLE
fanqienovel-downloader下遇到新的问题

### ISSUE THREAD

**Issue by yonggedebaqi** [ying-ck/fanqienovel-downloader#78]
fanqienovel-downloader下遇到新的问题
![2024-11-10 11-43-32屏幕截图](https://github.com/user-attachments/assets/9f1341ac-0eac-4444-8f82-d707911843c8)

**Comment by yonggedebaqi** [comment]
我使用的Ubuntu 24.04.1 LTS系统

**Comment by c1rcle-xy** [comment]
Linux运行好像就会出现这种问题，我在termux上也出现同样的报错

**Comment by afsfvr** [comment]
我在windows也遇到锅这种问题，把_default_progress方法->后面的 DownloadProgress改成 'NovelDownloader.DownloadProgress'，return后面的 DownloadProgress改成 self.DownloadProgress就解决了，你们也可以试试
