### ISSUE TITLE
网页版和本地版均无法打开

### ISSUE THREAD

**Issue by c1rcle-xy** [ying-ck/fanqienovel-downloader#79]
![屏幕截图 2024-11-13 132830](https://github.com/user-attachments/assets/b6314616-018a-417e-92a4-afc2a1ba0f74)
如图

**Comment by c1rcle-xy** [comment]
现在又正常了

**Comment by LinLei0102** [comment]
可以试试安装python看下？

**Comment by c1rcle-xy** [comment]
> 可以试试安装python看下？

python环境一切正常，依赖都装了

**Comment by LinLei0102** [comment]
> python环境一切正常，依赖都装了

嘶，我是即开即用的，没碰到出错。试试以管理员身份运行？

**Comment by LinLei0102** [comment]
> 我用的是python运行的py文件，不是release里的exe程序

。。。那没事了，我倒是有个服务器，但已经用某人提供的番茄API前端+后端用于看番茄小说用了，没法试试测试下这玩意了qwq

**Comment by LinLei0102** [comment]
> 能分享一下吗佬😘

https://github.com/[LYJ01X/fqweb](https://github.com/LYJ01X/fqweb)
这玩意需要你有一个番茄的SVIP账号（获取cookice）
它还搞了一个三合一版本，但要找开发者索取授权，好处是，无需SVIP账号。
他没开源，但我留着他的三合一源码

**Comment by LinLei0102** [comment]
> 能分享一下吗佬😘

补充：这玩意是配合“阅读app”的，本质上是一个番茄源

**Comment by c1rcle-xy** [comment]
> > 能分享一下吗佬😘
> 
> 补充：这玩意是配合“阅读app”的，本质上是一个番茄源

好的好的，非常感谢🥰

**Comment by LinLei0102** [comment]
> 好的好的，非常感谢🥰

。。。等会，我才发现他好像把主要代码删干净了= =，加我QQ：876990765，我丢你代码（安详入世）
