### ISSUE TITLE
txt打开章节乱序

### ISSUE THREAD

**Issue by dldldl0314** [ying-ck/fanqienovel-downloader#80]
txt打开章节乱序，虽然用网页打开章节顺序是正确的，但是txt中的章节还是乱的

**Comment by imzlh** [comment]
我也遇到了，第一章居然在最后，很奇怪

**Comment by imzlh** [comment]
看了一下源码，线程池并发导致的错误，变通方法是线程池设为1关闭并行

<img width="376" alt="image" src="https://github.com/user-attachments/assets/7e8a8bce-4dae-472f-9848-c542046de859">

**Comment by qxqycb** [comment]
> 看了一下源码，线程池并发导致的错误，变通方法是线程池设为1关闭并行
> 
> <img width="376" alt="image" src="https://github.com/user-attachments/assets/7e8a8bce-4dae-472f-9848-c542046de859">
> 

这样下载速度就没了

**Comment by imzlh** [comment]
> > 看了一下源码，线程池并发导致的错误，变通方法是线程池设为1关闭并行
> > <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/114276136/386919637-7e8a8bce-4dae-472f-9848-c542046de859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzA3NzcsIm5iZiI6MTczMTgzMDQ3NywicGF0aCI6Ii8xMTQyNzYxMzYvMzg2OTE5NjM3LTdlOGE4YmNlLTRkYWUtNDcyZi05ODQ4LWM1NDIwNDZkZTg1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwODAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjgxZTBiMWFhZmI5YzZmYzJlMWM1OWMxYzdjZmMxOGQ3NDNjM2NhZTEwNmVhZTM5ZTA1ODgyMTgyNDZkZWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J2LY12Rt8zsKtdnhic5yHHcMhdviAOg67_X_-cIG9v4">
> 
> 这样下载速度就没了

总比下载了还看不了好...我觉得应该使用asyncio，使用Array有序存储而不是混乱的Object和多线程并发

**Comment by qxqycb** [comment]
已修改
