### ISSUE TITLE
web版功能相关

### ISSUE THREAD

**Issue by LinLei0102** [ying-ck/fanqienovel-downloader#83]
web版.exe好像只能在线看，没法将小说下载到本地哎？

**Comment by c1rcle-xy** [comment]
web v1.0.0能下载，但是下载线程需要小于6，不然会乱序

**Comment by 76563** [comment]
同，我用的是web v1.0.0版本，但没找到下载后的本地文件在哪里

**Comment by c1rcle-xy** [comment]
> 同，我用的是web v1.0.0版本，但没找到下载后的本地文件在哪里

在src/novel_downloads文件夹里

**Comment by jsuone** [comment]
网页版下载的文件保存在temp的缓存目录下，每次退出程序就会清空，设置里没有看到修改保存路径的地方

**Comment by qxqycb** [comment]
已修改
