### ISSUE TITLE
v1.1.15下载的epub格式使用了各种阅读器都只能看封面简介和章节名称

### ISSUE THREAD

**Issue by liangjinghao** [ying-ck/fanqienovel-downloader#84]

**Comment by liangjinghao** [comment]
原来是大部分章节正文都没下载成功，这……
下载完也不踏实啊，不知道有没下载到，还要每章节查翻

**Comment by liangjinghao** [comment]
发现目录下的JSON格式化后拖放比较好检查是否缺失，建议生成的JSON文件格式化一下。

**Comment by qxqycb** [comment]
真的吗？我怎么没有问题？发个图片看看

**Comment by liangjinghao** [comment]
> 真的吗？我怎么没有问题？发个图片看看
不知是不是bookid批量下载造成的，下午我已经单个全新下载回来，现在正常
之前的json目录截图，文件大小明显太少的，打开就是这样，大部分章节没有正文
![json目录](https://github.com/user-attachments/assets/5403ca89-b79d-479a-b673-17c12756f0fc)
![json文本](https://github.com/user-attachments/assets/3f32faed-8361-45d9-b05f-30e53274f5a4)
