### ISSUE TITLE
web1.0.1版下载依旧出现乱序的情况

### ISSUE THREAD

**Issue by c1rcle-xy** [ying-ck/fanqienovel-downloader#87]
![Screenshot_2024-11-17-13-28-22-05_68e6fbd18cf87e713eb44152d67d0941.jpg](https://github.com/user-attachments/assets/dc09c906-6910-4118-a3f0-bd071ea5bf6e)

如图，下载线程为默认16

**Comment by c1rcle-xy** [comment]
而且web版的书库也不显示已下载的小说文件，只能cd到novel_downloads文件夹获取

**Comment by qxqycb** [comment]
啊？我还没有提交呢？
下周，现在上学去了

**Comment by c1rcle-xy** [comment]
> 啊？我还没有提交呢？
> 下周，现在上学去了

噢噢好的，我还以为更新了😂
