### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by qxqycb** [ying-ck/fanqienovel-downloader#9]
作者你好！
我在昨天给您的项目fanqienovel-downloader-v1.0.3添加了一个新功能：1. 正常模式 - 下载整本小说到一个文件；2. 分章保存模式 - 每个章节保存为单独的文件，
并且速度也加快了，
但是原来的保存一个json文件来更新的功能没有了
望准许
![屏幕截图 2024-08-14 184244](https://github.com/user-attachments/assets/84f39b60-25a5-4737-93bb-403b227d5f3f)
[源码.txt](https://github.com/user-attachments/files/16611734/default.txt)

**Comment by qxqycb** [comment]
新版本
修复了原来下载章节排序的问题
[源码2.txt](https://github.com/user-attachments/files/16612011/2.txt)

**Comment by ying-ck** [comment]
唔，好像也不是不行。
其实速度慢是因为防止封ip设置的随机延迟。我或许可以合并一下新功能？

**Comment by qxqycb** [comment]
OK

**Comment by qxqycb** [comment]
OK

**Comment by qxqycb** [comment]
OK
我可以试一下在你v1.05的基础上修改一下

**Comment by ying-ck** [comment]
其实保存为txt的本质就是将json格式的文件{章节名:章节内容，…}转换为纯文本，只要换方式处理就可以实现分章保存。

**Comment by qxqycb** [comment]
用正则表达式，之前做过
pattern = r'第[0-9一二三四五六七八九十百千万零一二三四五六七八九十]+\s*章|番外'

def split_novel(file_path, pattern, target_encoding='utf-8'):
    try:
        # 使用chardet检测原始编码
        with open(file_path, 'rb') as f:
            raw_content = f.read()
        detected_encoding = chardet.detect(raw_content)['encoding'] or target_encoding

        # 读取文件内容
        with open(file_path, 'r', encoding=detected_encoding) as file:
            content = file.read()

        # 使用正则表达式分割内容
        chapters = re.split(pattern, content)

        # 过滤掉空的章节标题和内容
        chapters = [chap.strip() for chap in chapters if chap.strip()]

        # 保存章节到新文件
        for chapter_number, chapter in enumerate(chapters, start=1):
            if chapter:  # 确保章节内容不为空
                chapter_filename = f"{os.path.splitext(file_path)[0]}_第_{chapter_number}.txt"
                with open(chapter_filename, 'w', encoding=target_encoding) as new_file:
                    new_file.write(chapter)
                print(f"章节 {chapter_number} 已保存为: {chapter_filename}")

    except Exception as e:
        print(f"处理文件时发生错误: {e}")

**Comment by qxqycb** [comment]
> 唔，好像也不是不行。 其实速度慢是因为防止封ip设置的随机延迟。我或许可以合并一下新功能？

关于防止封ip，我试了几十次，一次性下了一千多章，也没有被封，可能不用考虑吧

**Comment by ying-ck** [comment]
我的意思其实是使用json模块读取 小说名.json 后，就有了一个完整内容的字典，可以直接调用不用再分章节。

**Comment by qxqycb** [comment]
理解了，也可以

**Comment by ying-ck** [comment]
好了，到点睡觉，明日细谈

**Comment by qxqycb** [comment]
晚安，祝你做个好梦！
提个意见：把record.json和config.json用一个单独的文件夹装起来；把下载的小说用另一个文件夹装。
以上操作可以防止一些用户不懂这些是什么然后删了

**Comment by qxqycb** [comment]
# 新版：
import os
import requests
from bs4 import BeautifulSoup
import re
import tkinter as tk
from tkinter import filedialog
from urllib.parse import urljoin


def download_single_chapter(chapter_url, chapter_name, file):
    try:
        response = requests.get(chapter_url, headers={'User-Agent': 'Mozilla/5.0'})
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        # 假设章节内容被包含在一个id为"content"的div中，这需要根据实际网站的结构进行调整
        content = soup.find('div', id='content')
        if content:
            # 移除HTML标签并处理换行符
            text = content.get_text(strip=True, separator='\n')
            file.write(f"{chapter_name}\n{text}\n")  # 写入章节名称和内容
        else:
            print(f"章节内容未找到: {chapter_url}")
    except requests.RequestException as e:
        print(f"下载章节出错: {e}")

# 验证URL函数
def is_valid_url(url):
    regex = re.compile(
        r'^(https?:\/\/)?'  # 匹配 http:// 或 https:// 或什么都不匹配
        r'(\w+\.)*'  # 匹配域名
        r'(\w+)'  # 匹配顶级域
        r'(\/[^\s]*)?$',  # 匹配可选的路径
        re.IGNORECASE
    )
    return re.match(regex, url) is not None

# 获取小说信息函数
def get_novel_info(novel_directory_url):
    try:
        response = requests.get(novel_directory_url, headers={'User-Agent': 'Mozilla/5.0'})
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        # 更新选择器以匹配实际网站的结构
        chapter_selector = '#list dl dd a'  # 新的选择器匹配所有章节链接
        chapters = soup.select(chapter_selector)

        # 提取网站的域名部分
        domain = novel_directory_url.split('/book/')[0]

        chapter_urls = []
        chapter_names = []
        for a in chapters:
            href = a['href']
            # 检查href是否以'/'开头，如果是，则使用urljoin来避免重复添加域名
            if href.startswith('/'):
                full_url = urljoin(domain, href)
            else:
                full_url = urljoin(novel_directory_url, href)
            chapter_urls.append(full_url)
            chapter_names.append(a.get_text(strip=True))

        return chapter_urls, chapter_names
    except requests.RequestException as e:
        print(f"无法获取小说信息: {e}")
        return [], []
def clean_filename(filename):
    return re.sub(r'[\\/*?:"<>|]', '_', filename)

# 下载章节函数
def download_chapters(chapter_urls, chapter_names, output_dir, mode):
    total_chapters = len(chapter_urls)
    downloaded_chapters = 0

    def update_progress():
        nonlocal downloaded_chapters
        downloaded_chapters += 1
        progress = (downloaded_chapters / total_chapters) * 100
        print(f"下载进度: {progress:.2f}% ({downloaded_chapters}/{total_chapters})", end="\r")

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    start_index = 9

    if mode == 'complete':
        novel_filename = os.path.join(output_dir, "novel.txt")
        with open(novel_filename, 'w', encoding='utf-8') as file:
            for chapter_url, chapter_name in zip(chapter_urls[start_index:], chapter_names[start_index:]):
                download_single_chapter(chapter_url, chapter_name, file)

    elif mode == 'separate':
        for chapter_url, chapter_name in zip(chapter_urls[start_index:], chapter_names[start_index:]):
            chapter_filename = os.path.join(output_dir, clean_filename(f"{chapter_name}.txt"))

            download_single_chapter(chapter_url, chapter_name, open(chapter_filename, 'w', encoding='utf-8'))

    print(f"\n所有章节已成功下载到 {output_dir}。")



# 用户选择保存位置
def get_save_directory():
    root = tk.Tk()
    root.withdraw()  # 不显示根窗口
    return filedialog.askdirectory(title="选择保存目录")

# Debug模式函数
def debug_mode(novel_directory_url):
    chapter_urls, chapter_names = get_novel_info(novel_directory_url)
    if chapter_urls and chapter_names:
        print("Debug模式：")
        for url, name in zip(chapter_urls, chapter_names):
            print(f"URL: {url}, Name: {name}")
    else:
        print("无法获取章节信息。")

# 主函数
def main():
    while True:
        print("请选择以下操作：")
        print("1. 进入正常模式 - 下载整本小说到一个文件")
        print("2. 进入分章保存模式 - 每个章节保存为单独的文件")
        print("3. 进入Debug模式 - 打印调试信息")
        print("4. 退出程序")
        user_input = input("请输入您的选择（1~4）:（默认“1”）")

        if user_input == '4':
            print("程序已退出。")
            break

        try:
            user_input = int(user_input)
            if user_input < 1 or user_input > 4:
                print("无效的输入，请输入1到4之间的数字。")
                continue

            novel_directory_url = 'https://www.bqzw789.org/620/620227/'


            chapter_urls, chapter_names = get_novel_info(novel_directory_url)
            if not chapter_urls or not chapter_names:
                print("无法获取小说章节信息，请检查网址是否正确。")
                continue

            output_dir = get_save_directory()  # 修正为正确的函数名
            if user_input == 1:
                download_chapters(chapter_urls, chapter_names, output_dir, 'complete')
            elif user_input == 2:
                download_chapters(chapter_urls, chapter_names, output_dir, 'separate')
            elif user_input == 3:
                debug_mode(novel_directory_url)
        except ValueError:
            print("无效的输入，请输入数字。")

if __name__ == "__main__":
    main()

**Comment by qxqycb** [comment]
# 新版，基于v1.05修改
## 修改了一些功能：
1.把record.json和config.json用一个单独的文件夹(data)储存；
2.把下载的小说用另一个文件夹(“小说名+.txt”)储存；
3.把用于检查更新的（小说名+.json）的json文件储存"data"文件夹中新建一个"小说名"文件夹中；
4.把open方式改为with open，防止打开和保存文件时出错
[Uploading 源码.txt…]()

**Comment by ying-ck** [comment]
我把你的代码稍微改了改，恢复了断点重下的功能并减少了磁盘占用。删除了sort来保持章节顺序等。
但是，使用pyinstaller打包后居然无法创建文件夹!
或许只能用batch命令行试一下了。

**Comment by ying-ck** [comment]
还在使用nuitak尝试中

**Comment by qxqycb** [comment]
你把你改的代码发给我，我试一试

**Comment by ying-ck** [comment]
[fanqienovel-downloader-v1.0.6.txt](https://github.com/user-attachments/files/16621339/fanqienovel-downloader-v1.0.6.txt)

**Comment by ying-ck** [comment]
ok，解决了

**Comment by ying-ck** [comment]
只要使用相对路径就行了

**Comment by qxqycb** [comment]
可以添加一个退出的代码，例如：
print('\n输入书的id直接下载\n输入下面的数字进入其他功能:')
    print('1. 更新小说列表')
    print('2. 设置')
    print('3.退出')
    elif inp == '3':
        print('退出程序')
        # 退出程序
        break

**Comment by ying-ck** [comment]
行

**Comment by qxqycb** [comment]
防止用户下载过程中强制退出

**Comment by ying-ck** [comment]
其实没关系，毕竟每5章存一次，打开就可以继续下

**Comment by ying-ck** [comment]
那么我发布了啊

**Comment by qxqycb** [comment]
等一下

**Comment by qxqycb** [comment]
算了，发吧

**Comment by qxqycb** [comment]
> ![Screenshot_20240815_072708_com.yujian.ResideMenuDemo.jpg](https://private-user-images.githubusercontent.com/107254798/358036677-3c7e1b3e-a43c-432d-9697-14f68572c4bd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDMwNzUsIm5iZiI6MTcyMzcwMjc3NSwicGF0aCI6Ii8xMDcyNTQ3OTgvMzU4MDM2Njc3LTNjN2UxYjNlLWE0M2MtNDMyZC05Njk3LTE0ZjY4NTcyYzRiZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNjE5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmFmZGY1NmEyYTJmNDAwZDVkYjZlZDgxYjQ1YzQwMWM4MzExYTljNTY5ODlhYjgzMDI1MTY0M2RjMGQwNzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UroejA_ZAFluRWkLMeXkFqxEW3zgY-ZlaJBVzqPhk_Y)
> 
> 早上根本打不开github，现在终于可以看了。你可以发一个拉取请求合并代码。

找到原因了，一模一样
[原因](https://www.36kr.com/p/2906814970534787)

**Comment by ying-ck** [comment]
天呐，我还以为是我的问题。
