### ISSUE TITLE
WEB版本: 1.0.1的一些问题

### ISSUE THREAD

**Issue by baiheyyds** [ying-ck/fanqienovel-downloader#91]
用了下大佬的新版本，发现两个明显的问题（PS：我是win10系统clone下载的项目）。
1、EPUB下载的书籍没有简介和封面了（以前是有的）
2、清理缓存功能不生效（右下角报错：清理缓存失败: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.）

**Comment by qxqycb** [comment]
已修复

**Comment by baiheyyds** [comment]
测试了一下最新的1.1.16版本，发现问题依然存在......
