### ISSUE TITLE
exe文件打开报错，不管是直接打开还是poweshell都一样

### ISSUE THREAD

**Issue by frederickgithub** [ying-ck/fanqienovel-downloader#96]
版本：fanqienovel-downloader-v1.1.16.exe
操作系统：windows7sp1

错误截图如下
![bug](https://github.com/user-attachments/assets/2ae259ab-8f2e-41ff-ad7d-f4325293d287)

**Comment by xingyan118** [comment]
可能是网络问题，你看看有没有挂梯子，或在不在国内？

**Comment by hscui** [comment]
应该是开了Clash，这个软件和Clash好像有冲突，把Clash关了就可以了。

**Comment by qxqycb** [comment]
关代理
